// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeMUOUFCTV9qtbGbOK4f1-n-Io7yvTI_o',
    appId: '1:992200673077:web:6b068a8898a8165ae3ee7c',
    messagingSenderId: '992200673077',
    projectId: 'procv-49cc2',
    authDomain: 'procv-49cc2.firebaseapp.com',
    storageBucket: 'procv-49cc2.appspot.com',
    measurementId: 'G-YG7RKWQRRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5mlD2aKJ3wfSE0LFrP6-usdovobSrLU',
    appId: '1:992200673077:android:d5852580cc23344ee3ee7c',
    messagingSenderId: '992200673077',
    projectId: 'procv-49cc2',
    storageBucket: 'procv-49cc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLvMwv6oej3W0QqYUTnUjWbEP5kWSAzZc',
    appId: '1:992200673077:ios:d8f2dffc046a03b6e3ee7c',
    messagingSenderId: '992200673077',
    projectId: 'procv-49cc2',
    storageBucket: 'procv-49cc2.appspot.com',
    iosBundleId: 'com.example.proCv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLvMwv6oej3W0QqYUTnUjWbEP5kWSAzZc',
    appId: '1:992200673077:ios:040c8cb25b3d8d07e3ee7c',
    messagingSenderId: '992200673077',
    projectId: 'procv-49cc2',
    storageBucket: 'procv-49cc2.appspot.com',
    iosBundleId: 'com.example.proCv.RunnerTests',
  );
}
